name: crypto_converter
description: A cryptocurrency converter
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0-0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.0
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  google_fonts: ^3.0.1
  hydrated_bloc: ^8.0.0
  path_provider: ^2.0.3
  crypto_font_icons: ^1.0.1
  pull_to_refresh_flutter3: ^2.0.2
  flutter_services_binding: ^0.1.0
  json_annotation: ^4.4.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.1
  mocktail: ^0.3.0
  flutter_lints: ^2.0.1
  build_runner: ^2.4.10
  json_serializable: ^6.1.3
  coverage: ^1.0.4
  test: ^1.20.1
  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true
