name: crypto_converter
description: A cryptocurrency converter
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0-0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.3
  google_fonts: ^6.2.1
  hydrated_bloc: ^9.1.5
  path_provider: ^2.0.3
  crypto_font_icons: ^1.0.1
  pull_to_refresh_flutter3: ^2.0.2
  flutter_services_binding: ^0.1.0
  json_annotation: ^4.4.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.1
  mocktail: ^1.0.4
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.1.3
  coverage: ^1.9.0
  test: ^1.20.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
