name: coin_api
description: API Client for the Coin API.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.4
  json_annotation: ^4.4.0
  crypto_font_icons: ^1.0.1

dev_dependencies:
  coverage: ^1.0.4
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  mocktail: ^0.2.0
  test: ^1.20.1