name: coin_repository
description: A Dart repository which manages the cryptocurrency domain.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  http: ^0.13.4
  json_annotation: ^4.4.0
  coin_api:
    path: ../coin_api
  equatable: ^2.0.3
  

dev_dependencies:
  coverage: ^1.0.4
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  mocktail: ^0.2.0
  test: ^1.20.1