name: Flutter Analysis
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Run Flutter Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.3
      - name: Setup dependencies
        run: flutter pub get
      - name: Analyze codebase
        run: flutter analyze
